### ISSUE TITLE
question about the vocabulary list

### ISSUE THREAD

**Issue by Wang-Xiaodong1899** [chrisjmccormick/inspect_word2vec#9]
Hello ! I saw the vocabulary list, like following in vocabulary_01.txt:
Allanah_Munson
WINDS_WILL
nab_sexual_predators
By_Alexandra_Barham
Mayor_Noramie_Jasmin
Chief_Executive_Glenn_Tilton
Neil_Kinnock
Makoto_Tamada_JPN_Konica
abductor_muscle
visit_www.availability.sungard.com
Eury
Greenson
Y1A
Kathy_Dehner
anti_Westernism
Searight

I am confused why there are so many single words? In the training process, we just need some pairs (like Allanah_Munson) to train the skip-gram model. So what these single words work for?

**Comment by chrisjmccormick** [comment]
Hi! The vocabulary entries with underscores are actually "phrases", meaning words that commonly occur together. (The first and last names of public figures are good examples, since these are often together).

The word pairs you're referring to are actually created by selecting two separate entries from the vocabulary. 

Hope that clears it up!
